import type {
  AttendanceRecord,
  Certificate,
  Event,
  NotificationItem,
  Organization,
  Registration,
  RolePermission,
  StaffMember,
  Ticket,
  User,
} from "@/types";

export const DEMO_USERS: Record<string, User> = {
  participant: {
    id: "u1",
    universityId: "PU2023-CS-042",
    firstName: "Aarav",
    lastName: "Sharma",
    name: "Aarav Sharma",
    email: "aarav@pu.ac.in",
    role: "participant",
    department: "Computer Science & Engineering",
    course: "B.Tech CSE",
    year: "3rd Year",
    organization: "Computer Science Club",
    status: "active",
  },
  student: {
    id: "u1",
    universityId: "PU2023-CS-042",
    firstName: "Aarav",
    lastName: "Sharma",
    name: "Aarav Sharma",
    email: "aarav@pu.ac.in",
    role: "participant",
    department: "Computer Science & Engineering",
    course: "B.Tech CSE",
    year: "3rd Year",
    organization: "Computer Science Club",
    status: "active",
  },
  event_admin: {
    id: "u2",
    universityId: "PU-STAFF-104",
    firstName: "Priya",
    lastName: "Mehta",
    name: "Priya Mehta",
    email: "priya@pu.ac.in",
    role: "event_admin",
    department: "Information Technology",
    course: "Faculty / Convener",
    organization: "Tech Fest Committee",
    status: "active",
  },
  admin: {
    id: "u2",
    universityId: "PU-STAFF-104",
    firstName: "Priya",
    lastName: "Mehta",
    name: "Priya Mehta",
    email: "priya@pu.ac.in",
    role: "event_admin",
    department: "Information Technology",
    course: "Faculty / Convener",
    organization: "Tech Fest Committee",
    status: "active",
  },
  super_admin: {
    id: "u3",
    universityId: "PU-ADMIN-001",
    firstName: "Dr. Rajesh",
    lastName: "Kumar",
    name: "Dr. Rajesh Kumar",
    email: "admin@pu.ac.in",
    role: "super_admin",
    organization: "PU Administration",
    status: "active",
  },
  platform_admin: {
    id: "u4",
    universityId: "PU-SYS-000",
    firstName: "System",
    lastName: "Administrator",
    name: "System Administrator",
    email: "superadmin@pu.ac.in",
    role: "platform_admin",
    organization: "PUVerse Platform",
    status: "active",
  },
};

export const ALL_USERS: User[] = [
  DEMO_USERS.participant,
  DEMO_USERS.event_admin,
  DEMO_USERS.super_admin,
  {
    id: "u5",
    universityId: "PU2023-ECE-118",
    firstName: "Neha",
    lastName: "Patel",
    name: "Neha Patel",
    email: "neha@pu.ac.in",
    role: "participant",
    department: "Electronics & Communication",
    course: "B.Tech ECE",
    year: "2nd Year",
    status: "active",
  },
  {
    id: "u6",
    universityId: "PU2022-ME-056",
    firstName: "Rahul",
    lastName: "Singh",
    name: "Rahul Singh",
    email: "rahul@pu.ac.in",
    role: "participant",
    department: "Mechanical Engineering",
    course: "B.Tech ME",
    year: "4th Year",
    status: "active",
  },
  {
    id: "u7",
    universityId: "PU2023-MBA-021",
    firstName: "Sneha",
    lastName: "Reddy",
    name: "Sneha Reddy",
    email: "sneha@pu.ac.in",
    role: "event_admin",
    department: "Management Studies",
    course: "MBA Tech",
    organization: "Cultural Committee",
    status: "active",
  },
  {
    id: "u8",
    universityId: "PU2024-AI-012",
    firstName: "Kabir",
    lastName: "Verma",
    name: "Kabir Verma",
    email: "kabir@pu.ac.in",
    role: "participant",
    department: "Computer Science & Engineering",
    course: "B.Tech AI & Data Science",
    year: "1st Year",
    status: "active",
  },
];

export const EVENTS: Event[] = [
  {
    id: "evt-1",
    title: "Annual Tech Symposium 2026",
    description: "A flagship technology conference featuring keynote speakers, workshops, and networking sessions for students and faculty.",
    about: "The Annual Tech Symposium is PU's premier tech gathering bringing together industry pioneers, researchers, and aspiring technologists. This year's theme focuses on Next-Gen Artificial Intelligence, Quantum Computing Fundamentals, and Sustainable Cloud Architectures.",
    eventCategory: "Conference",
    category: "Conference",
    startDate: "2026-08-15",
    endDate: "2026-08-15",
    startTime: "09:00 AM",
    endTime: "06:00 PM",
    venue: "Main Auditorium, Block A",
    eventMode: "Offline",
    bannerUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80",
    organization: "Tech Fest Committee",
    organizer: "Priya Mehta",
    organizerId: "u2",
    createdBy: "u2",
    capacity: 500,
    registered: 342,
    status: "PUBLISHED",
    submittedAt: "2026-07-01T08:30:00",
    publishedAt: "2026-07-02T10:00:00",
    hasCertificate: true,
    requiresApproval: false,
    aboutEvent: "The Annual Tech Symposium is PU's premier tech gathering bringing together industry pioneers, researchers, and aspiring technologists.",
    agenda: [
      { id: "ag-1", time: "09:00 AM", sessionTitle: "Opening Ceremony & Keynote Address", description: "Welcome speech by Dean of Engineering followed by vision talk on Autonomous AI Agents.", displayOrder: 1 },
      { id: "ag-2", time: "11:00 AM", sessionTitle: "Deep Dive: Cloud-Native Microservices", description: "Hands-on session architecting high-scale distributed systems with Kubernetes.", displayOrder: 2 },
      { id: "ag-3", time: "02:00 PM", sessionTitle: "Panel: Emerging Careers in DeepTech", description: "Interactive session with engineering directors from top Silicon Valley tech companies.", displayOrder: 3 },
      { id: "ag-4", time: "04:30 PM", sessionTitle: "Awards, Networking & Closing", description: "Recognition of top contributors, refreshers, and certificate distribution.", displayOrder: 4 },
    ],
    speakers: [
      { id: "sp-1", name: "Dr. Ananya Krishnan", designation: "Staff Research Scientist", organization: "Google DeepMind", bio: "Leading research on large-scale foundational reasoning models.", photoUrl: null, linkedinUrl: "https://linkedin.com", displayOrder: 1 },
      { id: "sp-2", name: "Rajiv Bansal", designation: "Principal Architect", organization: "Microsoft Research", bio: "20+ years building cloud-scale distributed computing systems.", photoUrl: null, linkedinUrl: "https://linkedin.com", displayOrder: 2 },
      { id: "sp-3", name: "Sneha Iyer", designation: "VP of Engineering", organization: "Razorpay", bio: "Scaling payment processing infrastructure to 10k+ TPS.", photoUrl: null, linkedinUrl: "https://linkedin.com", displayOrder: 3 },
    ],
    sponsors: [
      { id: "spo-1", name: "Google Cloud", logoUrl: null, description: "Official cloud infrastructure partner", websiteUrl: "https://cloud.google.com", sponsorshipLevel: "Title", displayOrder: 1 },
      { id: "spo-2", name: "GitHub Education", logoUrl: null, description: "Student developer pack sponsor", websiteUrl: "https://github.com", sponsorshipLevel: "Platinum", displayOrder: 2 },
      { id: "spo-3", name: "JetBrains", logoUrl: null, description: "IDE licenses and developer tooling sponsor", websiteUrl: "https://jetbrains.com", sponsorshipLevel: "Gold", displayOrder: 3 },
    ],
    registrationFields: [
      { id: "rf-1", label: "First Name", fieldType: "text", required: true, isSystem: true, displayOrder: 1 },
      { id: "rf-2", label: "Last Name", fieldType: "text", required: true, isSystem: true, displayOrder: 2 },
      { id: "rf-3", label: "University Email", fieldType: "email", required: true, isSystem: true, displayOrder: 3 },
      { id: "rf-4", label: "University ID", fieldType: "text", required: true, isSystem: true, displayOrder: 4 },
      { id: "rf-5", label: "Department", fieldType: "select", required: true, isSystem: false, options: ["Computer Science", "Information Technology", "Electronics", "Mechanical"], displayOrder: 5 },
      { id: "rf-6", label: "Dietary Preferences", fieldType: "select", required: false, isSystem: false, options: ["Vegetarian", "Non-Vegetarian", "Vegan", "No Preference"], displayOrder: 6 },
    ],
  },
  {
    id: "evt-2",
    title: "Inter-College Hackathon 2026",
    description: "48-hour continuous coding marathon solving real-world challenges across Fintech, AI, and Sustainability.",
    about: "Teams will collaborate over 48 hours to ideate, prototype, and demo functional software solutions. Mentors from partner companies guide teams through prototyping and judging.",
    eventCategory: "Competition",
    category: "Competition",
    startDate: "2026-09-05",
    endDate: "2026-09-07",
    startTime: "08:00 AM",
    endTime: "08:00 PM",
    venue: "Innovation Hub, Ground Floor",
    eventMode: "Offline",
    bannerUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&auto=format&fit=crop&q=80",
    organization: "Innovation Cell",
    organizer: "Priya Mehta",
    organizerId: "u2",
    createdBy: "u2",
    capacity: 200,
    registered: 156,
    status: "PUBLISHED",
    submittedAt: "2026-07-04T12:00:00",
    publishedAt: "2026-07-05T09:30:00",
    hasCertificate: true,
    requiresApproval: false,
    agenda: [
      { id: "ag-21", time: "08:00 AM", sessionTitle: "Team Check-in & Station Setup", description: "Verification of team credentials and workstation allocation.", displayOrder: 1 },
      { id: "ag-22", time: "10:00 AM", sessionTitle: "Hackathon Tracks & Problem Statements", description: "Revealing themes: Generative AI, Sustainable Tech, and Micro-Fintech.", displayOrder: 2 },
      { id: "ag-23", time: "02:00 PM", sessionTitle: "Mentor Checkpoint Round 1", description: "15 minutes review with assigned industry mentors.", displayOrder: 3 },
      { id: "ag-24", time: "05:00 PM", sessionTitle: "Final Demo & Pitches", description: "Top 10 finalists present live before jury.", displayOrder: 4 },
    ],
    speakers: [
      { id: "sp-21", name: "Arjun Nair", designation: "Head of Innovation", organization: "PU Innovation Hub", bio: "Incubating university tech ventures.", photoUrl: null, linkedinUrl: null, displayOrder: 1 },
    ],
    sponsors: [
      { id: "spo-21", name: "Polygon Labs", logoUrl: null, description: "Track prize sponsor", websiteUrl: "https://polygon.technology", sponsorshipLevel: "Title", displayOrder: 1 },
    ],
    registrationFields: [
      { id: "rf-21", label: "First Name", fieldType: "text", required: true, isSystem: true, displayOrder: 1 },
      { id: "rf-22", label: "Last Name", fieldType: "text", required: true, isSystem: true, displayOrder: 2 },
      { id: "rf-23", label: "University Email", fieldType: "email", required: true, isSystem: true, displayOrder: 3 },
      { id: "rf-24", label: "University ID", fieldType: "text", required: true, isSystem: true, displayOrder: 4 },
      { id: "rf-25", label: "GitHub Profile URL", fieldType: "text", required: true, isSystem: false, displayOrder: 5 },
      { id: "rf-26", label: "Team Size", fieldType: "select", required: true, isSystem: false, options: ["2 Members", "3 Members", "4 Members"], displayOrder: 6 },
    ],
  },
  {
    id: "evt-3",
    title: "Web3 & Decentralized Systems Bootcamp",
    description: "Intensive 3-day workshop on Ethereum, smart contract architecture, Solidity, and zero-knowledge proofs.",
    about: "Hands-on bootcamp designed for computer science students eager to transition from traditional backend web development to decentralized protocol architectures.",
    eventCategory: "Workshop",
    category: "Workshop",
    startDate: "2026-09-20",
    endDate: "2026-09-22",
    startTime: "10:00 AM",
    endTime: "04:00 PM",
    venue: "Lab 204, IT Block",
    eventMode: "Offline",
    bannerUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80",
    organization: "Computer Science Club",
    organizer: "Priya Mehta",
    organizerId: "u2",
    createdBy: "u2",
    capacity: 60,
    registered: 0,
    status: "PENDING_APPROVAL",
    submittedAt: "2026-08-01T11:20:00",
    hasCertificate: true,
    requiresApproval: true,
    agenda: [
      { id: "ag-31", time: "10:00 AM", sessionTitle: "Ethereum Virtual Machine & Smart Contracts", description: "Architecture fundamentals and bytecode execution.", displayOrder: 1 },
      { id: "ag-32", time: "01:30 PM", sessionTitle: "Security Auditing for Solidity", description: "Preventing reentrancy, overflow, and access control bugs.", displayOrder: 2 },
    ],
    speakers: [
      { id: "sp-31", name: "Rohan Varma", designation: "Smart Contract Auditor", organization: "OpenZeppelin", bio: "Audited multi-million dollar DeFi protocols.", photoUrl: null, linkedinUrl: null, displayOrder: 1 },
    ],
    sponsors: [],
    registrationFields: [
      { id: "rf-31", label: "First Name", fieldType: "text", required: true, isSystem: true, displayOrder: 1 },
      { id: "rf-32", label: "Last Name", fieldType: "text", required: true, isSystem: true, displayOrder: 2 },
      { id: "rf-33", label: "University Email", fieldType: "email", required: true, isSystem: true, displayOrder: 3 },
      { id: "rf-34", label: "University ID", fieldType: "text", required: true, isSystem: true, displayOrder: 4 },
      { id: "rf-35", label: "Programming Background", fieldType: "textarea", required: false, isSystem: false, displayOrder: 5 },
    ],
  },
  {
    id: "evt-4",
    title: "AI Robotics & Computer Vision Workshop",
    description: "Hands-on robotics workshop using ROS 2, OpenCV, and autonomous navigation algorithms.",
    about: "Build real-time object tracking and autonomous obstacle avoidance systems on edge devices like NVIDIA Jetson.",
    eventCategory: "Workshop",
    category: "Workshop",
    startDate: "2026-10-02",
    endDate: "2026-10-03",
    startTime: "09:30 AM",
    endTime: "05:00 PM",
    venue: "Robotics Lab, Mechanical Block",
    eventMode: "Offline",
    bannerUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&auto=format&fit=crop&q=80",
    organization: "Tech Fest Committee",
    organizer: "Priya Mehta",
    organizerId: "u2",
    createdBy: "u2",
    capacity: 45,
    registered: 0,
    status: "CHANGES_REQUESTED",
    superAdminRemarks: "Please verify safety guidelines for the hardware testing setup and provide speaker affiliation confirmation before resubmitting.",
    submittedAt: "2026-08-05T14:10:00",
    hasCertificate: true,
    requiresApproval: true,
    agenda: [
      { id: "ag-41", time: "09:30 AM", sessionTitle: "ROS 2 Architecture & Node Graphs", description: "Message passing and sensor telemetry.", displayOrder: 1 },
    ],
    speakers: [],
    sponsors: [],
    registrationFields: [
      { id: "rf-41", label: "First Name", fieldType: "text", required: true, isSystem: true, displayOrder: 1 },
      { id: "rf-42", label: "Last Name", fieldType: "text", required: true, isSystem: true, displayOrder: 2 },
      { id: "rf-43", label: "University Email", fieldType: "email", required: true, isSystem: true, displayOrder: 3 },
      { id: "rf-44", label: "University ID", fieldType: "text", required: true, isSystem: true, displayOrder: 4 },
    ],
  },
  {
    id: "evt-5",
    title: "University Career Expo & Networking Fair",
    description: "Direct interaction and on-campus interview sessions with 40+ leading corporate employers and tech firms.",
    about: "PU's premier placement networking event connecting graduating seniors and pre-final year students with recruiters across engineering, finance, management, and consulting.",
    eventCategory: "Career",
    category: "Career",
    startDate: "2026-10-15",
    endDate: "2026-10-15",
    startTime: "09:00 AM",
    endTime: "05:00 PM",
    venue: "Sports Complex Arena",
    eventMode: "Offline",
    bannerUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80",
    organization: "Tech Fest Committee",
    organizer: "Priya Mehta",
    organizerId: "u2",
    createdBy: "u2",
    capacity: 1000,
    registered: 0,
    status: "APPROVED",
    submittedAt: "2026-07-28T09:00:00",
    hasCertificate: false,
    requiresApproval: false,
    agenda: [
      { id: "ag-51", time: "09:00 AM", sessionTitle: "Recruiter Welcome & Company Stalls Open", description: "Check-in and resume distribution.", displayOrder: 1 },
    ],
    speakers: [],
    sponsors: [],
    registrationFields: [
      { id: "rf-51", label: "First Name", fieldType: "text", required: true, isSystem: true, displayOrder: 1 },
      { id: "rf-52", label: "Last Name", fieldType: "text", required: true, isSystem: true, displayOrder: 2 },
      { id: "rf-53", label: "University Email", fieldType: "email", required: true, isSystem: true, displayOrder: 3 },
      { id: "rf-54", label: "University ID", fieldType: "text", required: true, isSystem: true, displayOrder: 4 },
      { id: "rf-55", label: "Resume Drive Link", fieldType: "text", required: true, isSystem: false, displayOrder: 5 },
    ],
  },
  {
    id: "evt-6",
    title: "AI & Machine Learning Summit 2026",
    description: "Industry leaders discuss foundation models, agentic workflows, and ethical AI deployment.",
    about: "Completed summit featuring deep technical sessions on AI safety and production infrastructure.",
    eventCategory: "Conference",
    category: "Conference",
    startDate: "2026-07-10",
    endDate: "2026-07-10",
    startTime: "09:00 AM",
    endTime: "04:00 PM",
    venue: "Seminar Hall 1",
    eventMode: "Offline",
    bannerUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80",
    organization: "Tech Fest Committee",
    organizer: "Priya Mehta",
    organizerId: "u2",
    createdBy: "u2",
    capacity: 150,
    registered: 150,
    status: "COMPLETED",
    submittedAt: "2026-06-01T10:00:00",
    publishedAt: "2026-06-05T10:00:00",
    hasCertificate: true,
    requiresApproval: false,
    agenda: [],
    speakers: [],
    sponsors: [],
    registrationFields: [],
  },
];

export const REGISTRATIONS: Registration[] = [
  {
    id: "reg-1",
    eventId: "evt-1",
    eventTitle: "Annual Tech Symposium 2026",
    userId: "u1",
    studentName: "Aarav Sharma",
    studentEmail: "aarav@pu.ac.in",
    status: "registered",
    registeredAt: "2026-07-01T10:30:00",
    submittedAt: "2026-07-01T10:30:00",
    formVersion: 1,
    answers: { department: "Computer Science", dietary: "Vegetarian" },
  },
  {
    id: "reg-2",
    eventId: "evt-2",
    eventTitle: "Inter-College Hackathon 2026",
    userId: "u1",
    studentName: "Aarav Sharma",
    studentEmail: "aarav@pu.ac.in",
    status: "registered",
    registeredAt: "2026-07-05T14:20:00",
    submittedAt: "2026-07-05T14:20:00",
    formVersion: 1,
    answers: { github: "https://github.com/aaravsharma", teamSize: "3 Members" },
  },
];

export const TICKETS: Ticket[] = [
  {
    id: "tkt-1",
    eventId: "evt-1",
    eventTitle: "Annual Tech Symposium 2026",
    ticketCode: "PUV-EVT1-AARAV-7X2K",
    issuedAt: "2026-07-01T10:31:00",
    status: "active",
  },
  {
    id: "tkt-2",
    eventId: "evt-2",
    eventTitle: "Inter-College Hackathon 2026",
    ticketCode: "PUV-EVT2-AARAV-9M4P",
    issuedAt: "2026-07-05T14:21:00",
    status: "active",
  },
];

export const CERTIFICATES: Certificate[] = [
  {
    id: "cert-1",
    eventId: "evt-6",
    eventTitle: "AI & Machine Learning Summit 2026",
    issuedAt: "2026-07-11T10:00:00",
    downloadUrl: "#",
  },
];

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: "n1",
    title: "Registration Confirmed",
    message: "You are registered for Annual Tech Symposium 2026.",
    read: false,
    createdAt: "2026-07-01T10:31:00",
    type: "success",
  },
  {
    id: "n2",
    title: "Certificate Available",
    message: "Your certificate for AI & Machine Learning Summit is ready to download.",
    read: true,
    createdAt: "2026-07-11T10:05:00",
    type: "info",
  },
  {
    id: "n3",
    title: "Event Reminder",
    message: "Inter-College Hackathon starts in 5 days at Innovation Hub.",
    read: true,
    createdAt: "2026-08-31T08:00:00",
    type: "info",
  },
];

export const ORGANIZATIONS: Organization[] = [
  { id: "org-1", name: "Tech Fest Committee", type: "Committee", members: 45, events: 12, status: "active" },
  { id: "org-2", name: "Computer Science Club", type: "Club", members: 120, events: 8, status: "active" },
  { id: "org-3", name: "Innovation Cell", type: "Cell", members: 30, events: 5, status: "active" },
  { id: "org-4", name: "Cultural Committee", type: "Committee", members: 60, events: 15, status: "active" },
  { id: "org-5", name: "Robotics Club", type: "Club", members: 35, events: 4, status: "active" },
];

export const STAFF_MEMBERS: StaffMember[] = [
  { id: "s1", name: "Vikram Joshi", email: "vikram@pu.ac.in", role: "Scanner" },
  { id: "s2", name: "Ananya Das", email: "ananya@pu.ac.in", role: "Coordinator" },
  { id: "s3", name: "Karan Malhotra", email: "karan@pu.ac.in", role: "Help Desk" },
];

export const ATTENDANCE: AttendanceRecord[] = [
  { id: "att-1", studentName: "Aarav Sharma", studentEmail: "aarav@pu.ac.in", checkedInAt: "2026-07-10T09:05:00", method: "qr" },
  { id: "att-2", studentName: "Neha Patel", studentEmail: "neha@pu.ac.in", checkedInAt: "2026-07-10T09:12:00", method: "qr" },
];

export const ROLE_PERMISSIONS: RolePermission[] = [
  {
    id: "r1",
    name: "Participant",
    description: "Browse events, register, view tickets and certificates",
    permissions: ["events.read", "registrations.create", "tickets.read", "certificates.read"],
  },
  {
    id: "r2",
    name: "Event Admin",
    description: "Create and build events through multi-step form, manage owned events",
    permissions: ["events.create", "events.update", "events.publish", "registrations.read"],
  },
  {
    id: "r3",
    name: "Super Admin",
    description: "Approve, request changes, or reject events, assign/remove Event Admin role",
    permissions: ["events.approve", "events.reject", "users.assign_role", "organizations.manage"],
  },
];

export const ANALYTICS = {
  totalUsers: 4520,
  totalEvents: 156,
  totalRegistrations: 12480,
  attendanceRate: 87,
  activeOrganizations: 28,
  pendingApprovals: 2,
  monthlyRegistrations: [420, 580, 720, 890, 650, 780, 920],
  topEvents: [
    { name: "Annual Tech Symposium", registrations: 342 },
    { name: "Inter-College Hackathon", registrations: 156 },
    { name: "AI & ML Summit", registrations: 150 },
  ],
};

export function getEventById(id: string) {
  return EVENTS.find((e) => e.id === id);
}

export function getRegistrationsForEvent(eventId: string) {
  return REGISTRATIONS.filter((r) => r.eventId === eventId);
}
